### PR TITLE
Add multiple arch for the bdjuno and hasura builds.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16#-NRiHIdSEg5Gk79_sXos:-NRiHIdT2o74ofVuMZin:b-xq7bqv) (no related file):*
That is the image build by from this PR right ?



___
___
*[`Dockerfile` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16#-NRiHOFb9ja1Wl5qOye3:-NRiHOFb9ja1Wl5qOye4:b-4zv31) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/2b41a8adf7f84e9efb7e73112d8145b4974850bd/Dockerfile#L1)):*
> ```Dockerfile
> FROM --platform=$BUILDPLATFORM golang:1.18-alpine AS builder
> ```

I didn't know we should modify dockerfile I thought it just works out of box if you use `buildx`
What does this flag mean ?
___
*[`Dockerfile` line 6 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16#-NRiIds58AMNxU_fGPqq:-NRiIds58AMNxU_fGPqr:b-sb9ij9) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/2b41a8adf7f84e9efb7e73112d8145b4974850bd/Dockerfile#L6)):*
> ```Dockerfile
> COPY . ./
> ARG arch=x86_64
> ADD https://github.com/CosmWasm/wasmvm/releases/download/v1.1.1/libwasmvm_muslc.${arch}.a /lib/libwasmvm_muslc.${arch}.a
> ```

so we just updated to version we have inside crust right ?
___
*[`Dockerfile` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16#-NRiK5mv2CJ1Rj0ocUc8:-NRiK5mv2CJ1Rj0ocUc9:b7b2a2i) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/2b41a8adf7f84e9efb7e73112d8145b4974850bd/Dockerfile#L18)):*
> ```Dockerfile
> COPY database/schema /var/lib/postgresql/schema
> 
> CMD [ "bdjuno", "start" ]
> ```

minor: rollback pls )
___
*[`.github/workflows/build.yml` line 42 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16#-NRiKCsq-QC9QqylpAdz:-NRiKCsq-QC9QqylpAe-:b-4laqzu) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/2b41a8adf7f84e9efb7e73112d8145b4974850bd/.github/workflows/build.yml#L42)):*
> ```YAML
> 
>       - name: Build and push bdjuno
>         uses: docker/build-push-action@v4
> ```

do I understand it correctly `docker/build-push-action@v4` uses buildx under the hood right ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16#-NRiHIdSEg5Gk79_sXos:-NRl01GsBilyBkmaOthe:bfilje7) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

That is the image build by from this PR right ?



</blockquote></details>

Yes, it was built for the testing purpose. If you have the access you can remove it.

___
___
*[`Dockerfile` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16#-NRiHOFb9ja1Wl5qOye3:-NRl0BTa6G76Z1MYyFOP:bke0qnh) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/2b41a8adf7f84e9efb7e73112d8145b4974850bd/Dockerfile#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I didn't know we should modify dockerfile I thought it just works out of box if you use `buildx`
What does this flag mean ?
</blockquote></details>

Actualy it's optionaly to set the `BUILDPLATFORM` as default platform here since we run on the `amd64` and we know that it's `amd64`. We need it just to specify to use exactly that platform to be fetched initially to be built on. And if there is not such platform the buildX should say it.
___
*[`Dockerfile` line 6 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16#-NRiIds58AMNxU_fGPqq:-NRl0Y3i-asEZFFoP61Z:bgrpx6b) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/2b41a8adf7f84e9efb7e73112d8145b4974850bd/Dockerfile#L6)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so we just updated to version we have inside crust right ?
</blockquote></details>

Right, also this is the workaronud how to do build for the `arm64`. We build always with the dependencies for the `amd64` on `amd64`, but save it as an `arm64` because first we don't use the `wasm` in that image and second to build on `arm64` we need either `arm64` runner or use the croscompiltion which overcomplicated the build. 
___
*[`Dockerfile` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16#-NRiK5mv2CJ1Rj0ocUc8:-NRl18Ti0-fTDUX_GNY3:b-blmwff) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/2b41a8adf7f84e9efb7e73112d8145b4974850bd/Dockerfile#L18)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: rollback pls )
</blockquote></details>

Added new line.



_Code quote:_
```Dockerfile
COPY database/schema /var/lib/postgresql/schema
```

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/build.yml` line 42 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16#-NRiKCsq-QC9QqylpAdz:-NRl5uUV6FzH_WqDgA3J:b8azruv) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/2b41a8adf7f84e9efb7e73112d8145b4974850bd/.github/workflows/build.yml#L42)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do I understand it correctly `docker/build-push-action@v4` uses buildx under the hood right ?
</blockquote></details>

`docker/build-push-action@v4` is the latest `docker/build-push-action` and right, if you specily `platforms` it will use the build under the hood.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16#-NRiHIdSEg5Gk79_sXos:-NRm7aEG9ddHEYxQsNr7:bwunfib) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes, it was built for the testing purpose. If you have the access you can remove it.
</blockquote></details>

it is ok
just verifying 

___
___
*[`Dockerfile` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16#-NRiHOFb9ja1Wl5qOye3:-NRm85Eg94WDe_Vq0VkR:bv7rqbb) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/2b41a8adf7f84e9efb7e73112d8145b4974850bd/Dockerfile#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actualy it's optionaly to set the `BUILDPLATFORM` as default platform here since we run on the `amd64` and we know that it's `amd64`. We need it just to specify to use exactly that platform to be fetched initially to be built on. And if there is not such platform the buildX should say it.
</blockquote></details>

lets just quickly discuss this after daily & I will resolve and approve

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`Dockerfile` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16#-NRiHOFb9ja1Wl5qOye3:-NRmVB1iAk6c4civbYWc:b32w1t) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/2b41a8adf7f84e9efb7e73112d8145b4974850bd/Dockerfile#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets just quickly discuss this after daily & I will resolve and approve 
</blockquote></details>

Ok

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`Dockerfile` line 6 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16#-NRnETTMBsv5iR2jv_P7:-NRnETTMBsv5iR2jv_P8:b-tyjl57) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/19c7159ad4f000ce7f3dbf8ffb7a41dc2ed2233f/Dockerfile#L6)):*
> ```Dockerfile
> COPY . ./
> ARG arch=x86_64
> ADD https://github.com/CosmWasm/wasmvm/releases/download/v1.1.1/libwasmvm_muslc.${arch}.a /lib/libwasmvm_muslc.${arch}.a
> ```

add comment describing this magic pls

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`Dockerfile` line 6 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16#-NRnETTMBsv5iR2jv_P7:-NRqSjW8EEMi3Dgnzcgf:bb6un1j) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/19c7159ad4f000ce7f3dbf8ffb7a41dc2ed2233f/Dockerfile#L6)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

add comment describing this magic pls
</blockquote></details>

Done

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Pull request merged**
