### PR TITLE
Store auth module params

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/49)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/49)* status: 0 of 20 files reviewed, all discussions resolved (waiting on @keyleu, @miladz68, and @ysv)

___
*[`database/auth_params.go` line 13 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/49#-NoLiY3F-viVrauzj8TN:-NoLiY3F-viVrauzj8TO:b-v0aoq2) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/3b423a4dcc92cc293349fa727e75633890e32102/database/auth_params.go#L13)):*
> ```Go
> 
> // SaveAuthParams allows to store the given params into the database.
> func (db *Db) SaveAuthParams(params types.AuthParams) error {
> ```

Usually, we write tests for such functions which save the data to the DB.

**Review by ysv — DISMISSED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/49)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @wojtek-coreum)

___
*[`modules/auth/handle_genesis.go` line 43 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/49#-NoRRRaa0PZ4T7QfRpzF:-NoRRRaa0PZ4T7QfRpzG:b-vb436y) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/3b423a4dcc92cc293349fa727e75633890e32102/modules/auth/handle_genesis.go#L43)):*
> ```Go
> 	err = m.db.SaveAuthParams(types.NewAuthParams(genState.Params, doc.InitialHeight))
> 	if err != nil {
> 		return fmt.Errorf("error while storing genesis assetft params: %s", err)
> ```

typo: genesis auth params ?



_Code quote:_
```Go
genesis assetft
```

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/49)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @keyleu and @miladz68)

**Review by miladz68 — APPROVED** [review]
> Reviewed 19 of 20 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/49)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @keyleu)

**Pull request merged**
