### PR TITLE
Remove operator_address unique constraint.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/35)

### CODE REVIEW

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/35)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu, @miladz68, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/35)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/bdjuno/35#-Nis5stK22cnTrzUh_D8:-Nis5stLCU_pLue-8d_W:b-l3atog) (no related file):*
This is a bug in bdjuno, please create an issue in their repo

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/35)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/bdjuno/35#-Nis5stK22cnTrzUh_D8:-NisFatp05YptgNkzljo:b-k16rfa) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is a bug in bdjuno, please create an issue in their repo
</blockquote></details>

But the issue is created already.

___

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/35)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu, @miladz68, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/35)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu and @miladz68)

**Pull request merged**
