### PR TITLE
Add recipient to related accounts

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/38)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/38)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @miladz68, and @wojtek-coreum)

___
*[`modules/assetft/account_parser.go` line 17 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/38#-NjHzZM1Eh1F6mVAzvH3:-NjHzZM1Eh1F6mVAzvH4:b8axrdw) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1fd5cc2375041e55c078b8437d0b03e35c02afe8/modules/assetft/account_parser.go#L17)):*
> ```Go
> 		return []string{msg.Issuer}, nil
> 	case *assetfttypes.MsgMint:
> 		return []string{msg.Sender, msg.Recipient}, nil
> ```

I don't remember
Do we have empty recipient or it will be equal to issuer by default ?

Will this case be handled properly here ? no duplicates or empty string ?

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/38)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/38)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @ysv)

___
*[`modules/assetft/account_parser.go` line 17 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/38#-NjHzZM1Eh1F6mVAzvH3:-NjIGyo6DFXuGZqV5qTA:bdm6uh7) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1fd5cc2375041e55c078b8437d0b03e35c02afe8/modules/assetft/account_parser.go#L17)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't remember
Do we have empty recipient or it will be equal to issuer by default ?

Will this case be handled properly here ? no duplicates or empty string ?
</blockquote></details>

oh, you are right. It might be empty. Fixed.

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/38)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu and @miladz68)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/38)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu)

**Pull request merged**
