### PR TITLE
Update hasura schema

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/44)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/44)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @keyleu, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
Could you add the PR description with why you need this?

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/44#-:-Nm6GrGM3RnZykj_hgzr:bza6nmj)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @keyleu and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
I don't need this. @ysv assigned me a task to regenerate it

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/44#-:-Nm6IK9C4qZgpr7zxugw:b74a7ji)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @keyleu and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/44)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @keyleu)

**Pull request merged**
