### PR TITLE
feat: mark image with git tag if present

### PR DESCRIPTION
**Pull request by vertex451**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/10)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/10)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/build.yml` line 55 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/10#-NO96r8RCyEAKb4uKBCZ:-NO96r8RCyEAKb4uKBC_:bkqojma) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/f9a71de9a25774f4dbf4c804f895644e1ee5e1cc/.github/workflows/build.yml#L55)):*
> ```YAML
>             ${{ env.ORG }}/${{ env.HASURA_IMAGE_NAME }}:${{ env.VERSION }}
>             ${{ env.ORG }}/${{ env.HASURA_IMAGE_NAME }}:${{ env.SHA8 }}
>             ${{ env.ORG }}/${{ env.HASURA_IMAGE_NAME }}:latest
> ```

needs an empty line

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/10)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/build.yml` line 55 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/10#-NO96r8RCyEAKb4uKBCZ:-NO9HBsJ36pgFHyTmuPu:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/f9a71de9a25774f4dbf4c804f895644e1ee5e1cc/.github/workflows/build.yml#L55)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

needs an empty line
</blockquote></details>

Done.



_Code quote:_
```YAML
file: Dockerfile.hasura
```

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/10)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

___
*[`.github/workflows/build.yml` line 28 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/10#-NO9vbrL8zYnI_2spi7F:-NO9vbrL8zYnI_2spi7G:b-oyw5ut) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/220fcf285d3f69acf6935c1d905d2178adcc16f5/.github/workflows/build.yml#L28)):*
> ```YAML
>         run: |
>           echo "SHA8=${GITHUB_SHA::8}" >> $GITHUB_ENV
>           
> ```

what is this line about?

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/10)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`.github/workflows/build.yml` line 28 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/10#-NO9vbrL8zYnI_2spi7F:-NO9ytSA0Y29G913qbyk:b-u5pilg) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/220fcf285d3f69acf6935c1d905d2178adcc16f5/.github/workflows/build.yml#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what is this line about?
</blockquote></details>

It gets short git commit hash, and it was there before, so I decided to leave it as it is. (But it has 8 symbols, while git short commit has only 7)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Pull request merged**
