### PR TITLE
feat: remove height usage in action handlers

### PR DESCRIPTION
**Pull request by akhlopiachyi**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/56)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/56)* status: 0 of 26 files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi, @keyleu, @miladz68, and @ysv)

___
*[`modules/actions/handlers/account_balance.go` line 16 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/56#-Npe2PSGE16uKWIxqTtw:-Npe2PSGE16uKWIxqTtx:bjv2ez2) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/bfd158ff824c52bc51aba512361707cb2f0fd453/modules/actions/handlers/account_balance.go#L16)):*
> ```Go
> 		Msg("executing account balance action")
> 
> 	height, err := ctx.GetHeight(payload)
> ```

I would propose to do it differently.  How about setting zero (or -1) to the height if it is not provided? I expect it will take the latest block in that case.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/56)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, and @miladz68)

___
*[`modules/actions/handlers/account_balance.go` line 16 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/56#-Npe2PSGE16uKWIxqTtw:-Npt1OyU0Q9ZZb4ra4A4:b9fpomg) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/bfd158ff824c52bc51aba512361707cb2f0fd453/modules/actions/handlers/account_balance.go#L16)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would propose to do it differently.  How about setting zero (or -1) to the height if it is not provided? I expect it will take the latest block in that case.
</blockquote></details>

What are the benefits of this approach ? Because if we can minimize changes then I prefer this solution.

lets discuss on call

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/56)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @ysv)

___
*[`modules/actions/handlers/account_balance.go` line 16 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/56#-Npe2PSGE16uKWIxqTtw:-NptJP_BB59t2TMlON5P:bypqh0y) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/bfd158ff824c52bc51aba512361707cb2f0fd453/modules/actions/handlers/account_balance.go#L16)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

What are the benefits of this approach ? Because if we can minimize changes then I prefer this solution.

lets discuss on call
</blockquote></details>

That solution is exactly to minimize the changes.

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/56)* status: all files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi, @keyleu, and @miladz68)

___
*[`modules/actions/handlers/account_balance.go` line 16 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/56#-Npe2PSGE16uKWIxqTtw:-NptZYzw1DlFyMXpozLI:b-ambkhi) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/bfd158ff824c52bc51aba512361707cb2f0fd453/modules/actions/handlers/account_balance.go#L16)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

That solution is exactly to minimize the changes.
</blockquote></details>

discuss on call @akhlopiachyi pls do appropriate changes

**Pull request closed without merging**
