### PR TITLE
Update validator table indexes.

### PR DESCRIPTION
**Pull request by dzmitryhil**
Remove validator_info_operator_address_index and validator_info_self_delegate_address_index from validator_info table since it is possible to have them duplicated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31#-NiKPgxZ-d-ZI5uqUeRt:-NiKPgxZ-d-ZI5uqUeRu:bf3rfvq) (no related file):*
I don't understand the purpose of this PR. This are not unique indexes so why do we care about duplicates?

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31#-NiKPgxZ-d-ZI5uqUeRt:-NiZEJbI12c-aO9EcewJ:b-w1kiim) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't understand the purpose of this PR. This are not unique indexes so why do we care about duplicates?
</blockquote></details>

Right, updated. 

___

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, and @wojtek-coreum)

___
*[`database/schema/03-staking.sql` line 29 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31#-Ni_L_RNE0jgE1eXPs8c:-Ni_L_RNE0jgE1eXPs8d:bs87xb5) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/650519f143f810a8f2a3b3676061678e81d15cdf/database/schema/03-staking.sql#L29)):*
> ```TSQL
> (
>     consensus_address     TEXT   NOT NULL UNIQUE PRIMARY KEY REFERENCES validator (consensus_address),
>     operator_address      TEXT   NOT NULL,
> ```

so bdjuno doesn't have migrations define ?

How Artem Devops will apply this change ?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @keyleu, and @miladz68)

___
*[`database/schema/03-staking.sql` line 29 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31#-NicXsmA11DjGtI6RZg6:-NicXsmA11DjGtI6RZg7:b-89czmc) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/650519f143f810a8f2a3b3676061678e81d15cdf/database/schema/03-staking.sql#L29)):*
> ```TSQL
> (
>     consensus_address     TEXT   NOT NULL UNIQUE PRIMARY KEY REFERENCES validator (consensus_address),
>     operator_address      TEXT   NOT NULL,
> ```

Why operator address is not unique? In Cosmos SDK, one operator may create single validator only.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @miladz68, and @wojtek-coreum)

___
*[`database/schema/03-staking.sql` line 29 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31#-NicXsmA11DjGtI6RZg6:-NicinodBzikiCI_RblH:bl2kske) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/650519f143f810a8f2a3b3676061678e81d15cdf/database/schema/03-staking.sql#L29)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why operator address is not unique? In Cosmos SDK, one operator may create single validator only.
</blockquote></details>

Actually not.


Based on the history we can see that the `delegator` created 2 validators: [https://explorer.testnet-1.coreum.dev/coreum/accounts/testcore1w3lry34l3j8p94ktvzm5smp45q9mqm206ewvj8](https://explorer.testnet-1.coreum.dev/coreum/accounts/testcore1w3lry34l3j8p94ktvzm5smp45q9mqm206ewvj8)

 
As a result the `Operator address` can be the same the `testcorevalcons1star39u2c7jc6hk05vc9h2ls8uspz2yq7fdvhm` is different.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

___
*[`database/schema/03-staking.sql` line 29 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31#-Ni_L_RNE0jgE1eXPs8c:-Nicj9ozC3vfMPRhTroE:b-ykcl80) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/650519f143f810a8f2a3b3676061678e81d15cdf/database/schema/03-staking.sql#L29)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so bdjuno doesn't have migrations define ?

How Artem Devops will apply this change ?
</blockquote></details>

He has already applied it manually, should I keep it as is and add additional file to remove the constraint?

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, and @wojtek-coreum)

___
*[`database/schema/03-staking.sql` line 29 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31#-Ni_L_RNE0jgE1eXPs8c:-NidZQVO2fL-4MDeijjN:byeli39) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/650519f143f810a8f2a3b3676061678e81d15cdf/database/schema/03-staking.sql#L29)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

He has already applied it manually, should I keep it as is and add additional file to remove the constraint?
</blockquote></details>

IMO - yes
- first of all we should never modify it manually because this will cause inconsistency between different envs. Which I guess we already have
- All changes to DB should be done via migrations & committed to repo. If state of DBs could potentially be different within different envs migration should unify it. So here ideally we should add migration which remove indices if they exist 

I was always following this rules and it worked really well everywhere.
___
*[`database/schema/03-staking.sql` line 29 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31#-NicXsmA11DjGtI6RZg6:-Nid_6T189K8Nm7-Tb27:b-fb7a4k) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/650519f143f810a8f2a3b3676061678e81d15cdf/database/schema/03-staking.sql#L29)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually not.


Based on the history we can see that the `delegator` created 2 validators: [https://explorer.testnet-1.coreum.dev/coreum/accounts/testcore1w3lry34l3j8p94ktvzm5smp45q9mqm206ewvj8](https://explorer.testnet-1.coreum.dev/coreum/accounts/testcore1w3lry34l3j8p94ktvzm5smp45q9mqm206ewvj8)

 
As a result the `Operator address` can be the same the `testcorevalcons1star39u2c7jc6hk05vc9h2ls8uspz2yq7fdvhm` is different.
</blockquote></details>

yes, that was kinda surprising but looks valid

**Review by wojtek-coreum — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, and @miladz68)

___
*[`database/schema/03-staking.sql` line 29 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31#-NicXsmA11DjGtI6RZg6:-NideUBq5rB4iH_AG4-2:bb4pdmr) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/650519f143f810a8f2a3b3676061678e81d15cdf/database/schema/03-staking.sql#L29)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes, that was kinda surprising but looks valid
</blockquote></details>

I see, they only ensure that `ValidatorAddress` is unique

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @ysv)

___
*[`database/schema/03-staking.sql` line 29 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31#-Ni_L_RNE0jgE1eXPs8c:-Nidip2676a7FrPVXz-Y:b37cefy) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/650519f143f810a8f2a3b3676061678e81d15cdf/database/schema/03-staking.sql#L29)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IMO - yes
- first of all we should never modify it manually because this will cause inconsistency between different envs. Which I guess we already have
- All changes to DB should be done via migrations & committed to repo. If state of DBs could potentially be different within different envs migration should unify it. So here ideally we should add migration which remove indices if they exist 

I was always following this rules and it worked really well everywhere.
</blockquote></details>

It makes sense only if you use migration tools for it, but if the source is pure SQL, that won't work that way. The repo design is done to execute all scripts and define the final state, so the migration is out of the design.  So even if I add it as a separate file it won't solve the migration problem, just simplify the execution. 
___
*[`database/schema/03-staking.sql` line 29 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31#-NicXsmA11DjGtI6RZg6:-Nidj5v-5JguwGJpgdV2:bb77ufg) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/650519f143f810a8f2a3b3676061678e81d15cdf/database/schema/03-staking.sql#L29)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I see, they only ensure that `ValidatorAddress` is unique
</blockquote></details>

Yes.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, and @miladz68)

___
*[`database/schema/03-staking.sql` line 29 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31#-NijQCIFCMGGrxDKCGIO:-NijQCIFCMGGrxDKCGIP:b-5suc9c) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/d451238da1003647690ac89117e348b0d90ea098/database/schema/03-staking.sql#L29)):*
> ```TSQL
> (
>     consensus_address     TEXT   NOT NULL UNIQUE PRIMARY KEY REFERENCES validator (consensus_address),
>     --  TODO check that removal of operator_address UNIQUE modifier doesn't break new migration
> ```

so how will Artem Devops apply this change ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @ysv)

___
*[`database/schema/03-staking.sql` line 29 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31#-NijQCIFCMGGrxDKCGIO:-Nim_EcL6d4bhO7koOSu:bb77ufg) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/d451238da1003647690ac89117e348b0d90ea098/database/schema/03-staking.sql#L29)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so how will Artem Devops apply this change ?
</blockquote></details>

Yes.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @ysv)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu and @miladz68)

**Pull request closed without merging**
