### PR TITLE
feat: customparams params

### PR DESCRIPTION
**Pull request by dzmitryhil**
## Description

Add support of the customparams params for the indexer and hasura.

## API Query examples

Example of the GraphQL request:

```
query MyQuery {
  customparams_params {
    staking_params
  }
}

```

Example of the GraphQL response:
```
{
  "data": {
    "customparams_params": [
      {
        "staking_params": {
          "min_self_delegation": "10000000"
        }
      }
    ]
  }
}
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/5)

### CODE REVIEW

**Review by miladz68 — COMMENTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/5)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`README.md` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/bdjuno/5#-NKIeRYnA5YKjFvo2_Vx:-NKIeRYnA5YKjFvo2_Vy:blncx7a) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/81867f5937599131ba7ff79756d74b0418e13db8/README.md#L75)):*
> ```Markdown
> In case you want to integrate the indexing if the custom types, for example parameters,
> that [PR](https://github.com/CoreumFoundation/bdjuno/pull/4)
> can be taken as a reference implementation.
> ```

non-blocking
no empty line
___
*[`database/customparams_params.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/bdjuno/5#-NKIef62Bx-clSyggOkd:-NKIef62Bx-clSyggOke:b-oyyjj6) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/81867f5937599131ba7ff79756d74b0418e13db8/database/customparams_params.go#L14)):*
> ```Go
> // SaveCustomParamsParams saves the given x/customparams parameters inside the database
> func (db *Db) SaveCustomParamsParams(params *types.CustomParamsParams) error {
> ```

non-blocking
unneccesary leading new line 
___
*[`hasura/metadata/databases/bdjuno/tables/tables.yaml` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/bdjuno/5#-NKIf-xG6giKn3AcWXl_:-NKIf-xG6giKn3AcWXla:bxj23s1) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/81867f5937599131ba7ff79756d74b0418e13db8/hasura/metadata/databases/bdjuno/tables/tables.yaml#L44)):*
> ```YAML
> - "!include public_vesting_period.yaml"
> - "!include public_feemodel_params.yaml"
> - "!include public_customparams_params.yaml"
> ```

non-blocking
no new line at the end of file

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`README.md` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/bdjuno/5#-NKIeRYnA5YKjFvo2_Vx:-NKIjhYi1G9TA7Ztyg8n:b-896fix) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/81867f5937599131ba7ff79756d74b0418e13db8/README.md#L75)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non-blocking
no empty line
</blockquote></details>

Done.



_Code quote:_
```Markdown
can be taken as a reference implementation.
```
___
*[`database/customparams_params.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/bdjuno/5#-NKIef62Bx-clSyggOkd:-NKIjld73u95ReREerD9:b-896fix) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/81867f5937599131ba7ff79756d74b0418e13db8/database/customparams_params.go#L14)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non-blocking
unneccesary leading new line 

</blockquote></details>

Done.



_Code quote:_
```Go
CustomParamsParams saves the given x/customparams parameters in
```
___
*[`hasura/metadata/databases/bdjuno/tables/tables.yaml` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/bdjuno/5#-NKIf-xG6giKn3AcWXl_:-NKIjpMx6lRxXH1jInjO:b-896fix) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/81867f5937599131ba7ff79756d74b0418e13db8/hasura/metadata/databases/bdjuno/tables/tables.yaml#L44)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non-blocking
no new line at the end of file
</blockquote></details>

Done.



_Code quote:_
```YAML
!include public_customparams_params.yaml"
```

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 17 of 20 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Pull request merged**
