### PR TITLE
fix: update periods to update token_price and token_price_history

### PR DESCRIPTION
**Pull request by akhlopiachyi**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/67)

### CODE REVIEW

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/67)* status: all files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi, @dzmitryhil, @miladz68, and @ysv)

___
*[`modules/pricefeed/handle_periodic_operations.go` line 27 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/67#-NzCXtUV3yRy8iyQCb5E:-NzCXtUV3yRy8iyQCb5F:b78st5q) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/b030550dd3d74e051e531f9158466c2d1d516996/modules/pricefeed/handle_periodic_operations.go#L27)):*
> ```Go
> 	}
> 
> 	// Update the historical token prices every 1 hour
> ```

update the comment

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/67)* status: all files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi, @miladz68, and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/67#-:-NzTDVyp05ByQi0HsUTd:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi, @miladz68, and @ysv)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/67)* status: all files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi and @ysv)

**Review by dzmitryhil — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/67#-:-NzgJJf3-aY_JfPavmCH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi, @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/67)* status: all files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi, @wojtek-coreum, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Dismissed @wojtek-coreum from a discussion.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/67)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/67)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Pull request merged**
