### PR TITLE
Track validators missing proposals

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`modules/consensus/handle_block.go` line 52 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18#-NUMVjWx9XDrAom8VE46:-NUMVjWx9XDrAom8VE47:bydw20x) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/944399ad019f898c4f72f5acd6a70d842c2330a0/modules/consensus/handle_block.go#L52)):*
> ```Go
> }
> 
> func (m *Module) updateBlockTimeByValidator(block *tmctypes.ResultBlock, vals *tmctypes.ResultValidators) {
> ```

The block here might be not latest, so you need to track it.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18#-NUMdesk--l5wRc3F9UK:-NUMdesl1paDQGfaUbgw:b-jeommk) (no related file):*
Here is the sample output of the metric:

```
# HELP bdjuno_proposal Counts successful proposals.
# TYPE bdjuno_proposal summary
bdjuno_proposal_sum{validator="devcorevalcons1gtwg0dh0vd8txsu7z6yyc6p57j3jcy4xqz9yw4"} 11
bdjuno_proposal_count{validator="devcorevalcons1gtwg0dh0vd8txsu7z6yyc6p57j3jcy4xqz9yw4"} 11
bdjuno_proposal_sum{validator="devcorevalcons1lcxd6hq0reztm064t27wxujkfmjru576zp8ygc"} 10
bdjuno_proposal_count{validator="devcorevalcons1lcxd6hq0reztm064t27wxujkfmjru576zp8ygc"} 11
bdjuno_proposal_sum{validator="devcorevalcons1mf0y3xzl7c5qe87tghhkjqstm529acunt7fkya"} 11
bdjuno_proposal_count{validator="devcorevalcons1mf0y3xzl7c5qe87tghhkjqstm529acunt7fkya"} 11
bdjuno_proposal_sum{validator="devcorevalcons1sw6gj7k50fh3ddnuqp2g4uku6rvm5akk6ekest"} 11
bdjuno_proposal_count{validator="devcorevalcons1sw6gj7k50fh3ddnuqp2g4uku6rvm5akk6ekest"} 11
bdjuno_proposal_sum{validator="devcorevalcons1zjvnzzx073549vcsjlhypjqm2hemnxyk64w97m"} 5
bdjuno_proposal_count{validator="devcorevalcons1zjvnzzx073549vcsjlhypjqm2hemnxyk64w97m"} 10
```

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18#-NUMdesk--l5wRc3F9UK:-NUMdwfx0psky2v_X6Th:b-yxwc8m) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Here is the sample output of the metric:

```
# HELP bdjuno_proposal Counts successful proposals.
# TYPE bdjuno_proposal summary
bdjuno_proposal_sum{validator="devcorevalcons1gtwg0dh0vd8txsu7z6yyc6p57j3jcy4xqz9yw4"} 11
bdjuno_proposal_count{validator="devcorevalcons1gtwg0dh0vd8txsu7z6yyc6p57j3jcy4xqz9yw4"} 11
bdjuno_proposal_sum{validator="devcorevalcons1lcxd6hq0reztm064t27wxujkfmjru576zp8ygc"} 10
bdjuno_proposal_count{validator="devcorevalcons1lcxd6hq0reztm064t27wxujkfmjru576zp8ygc"} 11
bdjuno_proposal_sum{validator="devcorevalcons1mf0y3xzl7c5qe87tghhkjqstm529acunt7fkya"} 11
bdjuno_proposal_count{validator="devcorevalcons1mf0y3xzl7c5qe87tghhkjqstm529acunt7fkya"} 11
bdjuno_proposal_sum{validator="devcorevalcons1sw6gj7k50fh3ddnuqp2g4uku6rvm5akk6ekest"} 11
bdjuno_proposal_count{validator="devcorevalcons1sw6gj7k50fh3ddnuqp2g4uku6rvm5akk6ekest"} 11
bdjuno_proposal_sum{validator="devcorevalcons1zjvnzzx073549vcsjlhypjqm2hemnxyk64w97m"} 5
bdjuno_proposal_count{validator="devcorevalcons1zjvnzzx073549vcsjlhypjqm2hemnxyk64w97m"} 10
```
</blockquote></details>

You see missed proposals by the last validator after I stopped it

___

**Review by miladz68 — DISMISSED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`modules/consensus/handle_block.go` line 52 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18#-NUMVjWx9XDrAom8VE46:-NV45t1W7QJk1QgEFmU2:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/944399ad019f898c4f72f5acd6a70d842c2330a0/modules/consensus/handle_block.go#L52)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The block here might be not latest, so you need to track it.
</blockquote></details>

Done.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`modules/consensus/handle_async_operations.go` line 11 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18#-NV4CHRNEly1voQDrJL7:-NV4CHRNEly1voQDrJL8:b-vnffqs) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/affc3acbb203a12a3f16513222bfe7eda74c0bb5/modules/consensus/handle_async_operations.go#L11)):*
> ```Go
> )
> 
> func (m *Module) RunAsyncOperations() {
> ```

Did you decide to use `RunAsyncOperations` to keep the state in it? If yes - then IMO it simpler to keep the state in the module, since now in the module you have a channel you send the message there and process (in a blocking way) in in the `RunAsyncOperations`. The same can be done in the module directly.
___
*[`modules/consensus/handle_async_operations.go` line 19 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18#-NV4E55o3IOFmuGG9-Zi:-NV4E55o3IOFmuGG9-Zj:b-rzhrg5) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/affc3acbb203a12a3f16513222bfe7eda74c0bb5/modules/consensus/handle_async_operations.go#L19)):*
> ```Go
> 	for p := range m.proposerQueue {
> 		// This handles the case when block is received in order.
> 		if expectedProposer := expectedProposers[p.Height]; expectedProposer != nil {
> ```

IMO, `comma ok idiom` is better to check the existence on the map.
___
*[`modules/consensus/handle_async_operations.go` line 37 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18#-NV4EP55D4qaKvFvQECg:-NV4EP55D4qaKvFvQECh:b-j1a8ib) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/affc3acbb203a12a3f16513222bfe7eda74c0bb5/modules/consensus/handle_async_operations.go#L37)):*
> ```Go
> 		// This is naive approach which might lead to loosing some measures, but it won't break statistics.
> 		if len(realProposers) > maxCacheSize {
> 			realProposers = map[int64]tmtypes.Address{}
> ```

Is it better to remove just one index with the lowest key value?
___
*[`modules/consensus/handle_block.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18#-NV4Ccf24UAfkV5UU7bj:-NV4Ccf24UAfkV5UU7bk:b-bhmrer) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/944399ad019f898c4f72f5acd6a70d842c2330a0/modules/consensus/handle_block.go#L59)):*
> ```Go
> 	expectedNextProposer := vals.Validators[0]
> 	if len(vals.Validators) > 1 {
> 		for _, v := range vals.Validators[1:] {
> ```

What is we have just one validator (possible for the znet)?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18)* status: all files reviewed, 5 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`modules/consensus/handle_async_operations.go` line 37 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18#-NV4EP55D4qaKvFvQECg:-NV4L0BI0wBqochV2Cbd:b-5mogfc) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/affc3acbb203a12a3f16513222bfe7eda74c0bb5/modules/consensus/handle_async_operations.go#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is it better to remove just one index with the lowest key value?
</blockquote></details>

That's why I wrote that this way is naive, but it eliminates the need of going through all the indexes to find the minimum

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18)* status: all files reviewed, 5 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`modules/consensus/handle_async_operations.go` line 37 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18#-NV4EP55D4qaKvFvQECg:-NV4QyOX1hm0mJdn5eOM:b-sznzlx) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/affc3acbb203a12a3f16513222bfe7eda74c0bb5/modules/consensus/handle_async_operations.go#L37)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

That's why I wrote that this way is naive, but it eliminates the need of going through all the indexes to find the minimum
</blockquote></details>

Ok, anyways, the removal not 100% precise but acceptable.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`modules/consensus/handle_block.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18#-NV4Ccf24UAfkV5UU7bj:-NV4bS-4-_l0DrSJjDfc:b-80ta5i) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/944399ad019f898c4f72f5acd6a70d842c2330a0/modules/consensus/handle_block.go#L59)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is we have just one validator (possible for the znet)?
</blockquote></details>

then the expected next proposer is always:
```go
expectedNextProposer := vals.Validators[0]
```
___
*[`modules/consensus/handle_async_operations.go` line 11 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18#-NV4CHRNEly1voQDrJL7:-NV4bXwZBi9y42z9ZrB1:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/affc3acbb203a12a3f16513222bfe7eda74c0bb5/modules/consensus/handle_async_operations.go#L11)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Did you decide to use `RunAsyncOperations` to keep the state in it? If yes - then IMO it simpler to keep the state in the module, since now in the module you have a channel you send the message there and process (in a blocking way) in in the `RunAsyncOperations`. The same can be done in the module directly.
</blockquote></details>

Done.
___
*[`modules/consensus/handle_async_operations.go` line 19 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18#-NV4E55o3IOFmuGG9-Zi:-NV4bYZK6pse8Op2Vl2x:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/affc3acbb203a12a3f16513222bfe7eda74c0bb5/modules/consensus/handle_async_operations.go#L19)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO, `comma ok idiom` is better to check the existence on the map.
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

**Review by miladz68 — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/18)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

**Pull request merged**
