### PR TITLE
Fetch validators with all statuses when parsing validators

### PR DESCRIPTION
**Pull request by alinetskyi**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/48)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/48)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alinetskyi, @miladz68, @wojtek-coreum, and @ysv)

___
*[`modules/staking/utils_validators.go` line 213 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/48#-NnmJWgx2_cIvtWmOnfW:-NnmJWgx2_cIvtWmOnfX:b8c7idw) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/87c1067e3b39a39f6f033c7886811f61baf54b92/modules/staking/utils_validators.go#L213)):*
> ```Go
> 	}
> 
> 	validators, _, err := m.GetValidatorsWithStatus(block.Height, stakingtypes.Bonded.String())
> ```

Looks logical, did you test it?

**Review by alinetskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/48)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`modules/staking/utils_validators.go` line 213 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/48#-NnmJWgx2_cIvtWmOnfW:-Nnmi8wL9X6pcDbsyLgn:boutomz) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/87c1067e3b39a39f6f033c7886811f61baf54b92/modules/staking/utils_validators.go#L213)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Looks logical, did you test it?
</blockquote></details>

Yes, tested with a separate instance, seems to work as expected

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/48)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/48)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Pull request merged**
