### PR TITLE
ci: added release workflow

### PR DESCRIPTION
**Pull request by vertex451**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/6)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`.github/workflows/release.yml` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/bdjuno/6#-NLPOZ4T14C-hPcdad5K:-NLPOZ4T14C-hPcdad5L:b-o6w2mh) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/94e34a8ac6a507711349afd2a1ca128dd7aadc31/.github/workflows/release.yml#L25)):*
> ```YAML
>         with:
>           generate_release_notes: true
>       - name: Release-candidate
> ```

What do you release here?

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/release.yml` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/bdjuno/6#-NLPOZ4T14C-hPcdad5K:-NLPi1dk5e0vA40hnvbq:bps5tzp) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/94e34a8ac6a507711349afd2a1ca128dd7aadc31/.github/workflows/release.yml#L25)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What do you release here?
</blockquote></details>

Docker images will be added later.
But this is specific to this repo.
Do we want to release the repos without any artifacts? They will have tags to pin some state. Do we want to make those tags "released" ?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`.github/workflows/release.yml` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/bdjuno/6#-NLPOZ4T14C-hPcdad5K:-NLPjrC66viDX5W-fMwl:b-m1256m) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/94e34a8ac6a507711349afd2a1ca128dd7aadc31/.github/workflows/release.yml#L25)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

Docker images will be added later.
But this is specific to this repo.
Do we want to release the repos without any artifacts? They will have tags to pin some state. Do we want to make those tags "released" ?
</blockquote></details>

Af for me withoutd docker build and push we don't need it. But dowe push with the version as a tag now?

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/release.yml` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/bdjuno/6#-NLPOZ4T14C-hPcdad5K:-NLPoueTAW8PzQ9g-vHS:buy71k5) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/94e34a8ac6a507711349afd2a1ca128dd7aadc31/.github/workflows/release.yml#L25)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Af for me withoutd docker build and push we don't need it. But dowe push with the version as a tag now?
</blockquote></details>

not yet, this will be my next task

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`.github/workflows/release.yml` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/bdjuno/6#-NLPOZ4T14C-hPcdad5K:-NLQduC5540JFzNCFdSe:b32w1t) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/94e34a8ac6a507711349afd2a1ca128dd7aadc31/.github/workflows/release.yml#L25)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

not yet, this will be my next task
</blockquote></details>

Ok

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/release.yml` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/bdjuno/6#-NLPOZ4T14C-hPcdad5K:-NLQihtsB_zlSiXXxrtC:b-896fix) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/94e34a8ac6a507711349afd2a1ca128dd7aadc31/.github/workflows/release.yml#L25)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Ok
</blockquote></details>

Done.

**Pull request merged**
