### PR TITLE
Add pricefeed config to the default template.

### PR DESCRIPTION
**Pull request by dzmitryhil**
Example how to query

Current price (updated every minute)
```
  tokenPrice: token_price(limit: 100, where: {unit_name: {_eq: "coreum"}}) {
    marketCap: market_cap
    price
    timestamp
  }
```
History price (updated every hour)
```
  tokenPriceHistory: token_price_history(limit: 100, where: {unit_name: {_eq: "coreum"}}) {
    market_cap
    price
    timestamp
  }
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/23)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/23)* status: all files reviewed, 1 unresolved discussion (waiting on @bashash, @dzmitryhil, @miladz68, and @silverspase)

___
*[`config-sample.yaml` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/23#-NYI1L-47phE5lHT-uny:-NYI1L-47phE5lHT-unz:bmwilnd) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/b1d9242e1971d20bc8438af6d227bce718655e52/config-sample.yaml#L2)):*
> ```YAML
> chain:
>     bech32_prefix: YOUR_CHAIN_ACC_PREFIX
> ```

shouldn't it be `core`?

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bashash, @miladz68, and @silverspase)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bashash, @miladz68, and @silverspase)

___
*[`config-sample.yaml` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/23#-NYI1L-47phE5lHT-uny:-NYIOUHR34BCyQIvP1yb:b6zuzdc) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/b1d9242e1971d20bc8438af6d227bce718655e52/config-sample.yaml#L2)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

shouldn't it be `core`?
</blockquote></details>

 bech32_prefix depending on env might be different.

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bashash, @miladz68, and @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bashash and @silverspase)

**Pull request merged**
