### PR TITLE
Add bdjuno to sudo users

### PR DESCRIPTION
**Pull request by alinetskyi**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/21)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bashash, @silverspase, and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bashash, @silverspase, and @wojtek-coreum)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/21)* status: all files reviewed, 1 unresolved discussion (waiting on @alinetskyi, @bashash, @silverspase, and @wojtek-coreum)

___
*[`Dockerfile` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/21#-NXxeYijEEyJJIZyYGuh:-NXxeYijEEyJJIZyYGui:b-sti0zh) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/3384faa8ca8bbb3a550c12c0b84c542b16aa2f70/Dockerfile#L18)):*
> ```Dockerfile
> RUN apk add postgresql sudo
> RUN adduser -DG wheel bdjuno
> RUN sed -e 's;^# \(%wheel.*NOPASSWD.*\);\1;g' -i /etc/sudoers
> ```

@ysv @wojtek-coreum @miladz68 
We can keep the changes if we need them, but for my task I don't need them anymore.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/21)* status: all files reviewed, 1 unresolved discussion (waiting on @bashash, @miladz68, @silverspase, and @ysv)

___
*[`Dockerfile` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/21#-NXxeYijEEyJJIZyYGuh:-NXz1ot63D2EeIn58y3d:b-5scj02) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/3384faa8ca8bbb3a550c12c0b84c542b16aa2f70/Dockerfile#L18)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv @wojtek-coreum @miladz68 
We can keep the changes if we need them, but for my task I don't need them anymore.
</blockquote></details>

So is the problem with permissions fixed without this PR?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/21)* status: all files reviewed, 1 unresolved discussion (waiting on @bashash, @miladz68, @silverspase, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/21)* status: all files reviewed, 1 unresolved discussion (waiting on @bashash, @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/21)* status: all files reviewed, 1 unresolved discussion (waiting on @bashash, @miladz68, @silverspase, and @ysv)

___
*[`Dockerfile` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/21#-NXxeYijEEyJJIZyYGuh:-NY2Una74bEANNnrmMdS:b2nhswy) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/3384faa8ca8bbb3a550c12c0b84c542b16aa2f70/Dockerfile#L18)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

So is the problem with permissions fixed without this PR?
</blockquote></details>

Yes

**Comment by ysv** [comment]
closing it then

**Pull request closed without merging**
