### PR TITLE
Update coreum to the latest v4 version

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/68)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/68)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @keyleu, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/68)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, and @wojtek-coreum)

___
*[`Dockerfile.cosmwasm` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/68#-NzTcaSM3XHsTQmIzLVX:-NzTcaSM3XHsTQmIzLVY:b-l19fzq) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/08c9f519f480bcf5b00c570a53d1a3ad55186370/Dockerfile.cosmwasm#L3)):*
> ```
> 
> 
> FROM golang:1.21-alpine AS builder
> ```

by the way we got rid of wasm dependency in client import
Do we still need this Dockerfile WASM ?

If not needed lets create a task to remove

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/68)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @wojtek-coreum, and @ysv)

___
*[`Dockerfile.cosmwasm` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/68#-NzTcaSM3XHsTQmIzLVX:-NzWvdsG2PPLEJuSr9-Z:bs29jpw) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/08c9f519f480bcf5b00c570a53d1a3ad55186370/Dockerfile.cosmwasm#L3)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

by the way we got rid of wasm dependency in client import
Do we still need this Dockerfile WASM ?

If not needed lets create a task to remove
</blockquote></details>

We can remove it here as well.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/68)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @wojtek-coreum, and @ysv)

___
*[`Dockerfile.cosmwasm` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/68#-NzTcaSM3XHsTQmIzLVX:-NzWvpk31FX8-5hh2GuL:b18ar6n) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/08c9f519f480bcf5b00c570a53d1a3ad55186370/Dockerfile.cosmwasm#L3)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We can remove it here as well.
</blockquote></details>

Create the task for it.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/68)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @keyleu and @wojtek-coreum)

**Pull request merged**
