### PR TITLE
Remove not needed anymore WASM dependencies

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/37)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/37)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @miladz68, and @wojtek-coreum)

___
*[`Makefile` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/37#-NiuD6kQ4LM28BicFiZS:-NiuD6kQ4LM28BicFiZT:b-vohysh) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/3d543219d6f9e362786ba1fc741177e0e9461a19/Makefile#L39)):*
> ```Makefile
> else
> 	@echo "building bdjuno binary..."
> 	CGO_ENABLED=0 go build -mod=readonly $(BUILD_FLAGS) -o build/bdjuno ./cmd/bdjuno
> ```

I'm not sure how to combine env setting `CGO_ENABLED=0` & `@` in a single command
if you guys are aware LMK

If no i'm ok to keep it like this

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/37)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

___
*[`Makefile` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/37#-NiuD6kQ4LM28BicFiZS:-Nj69-He5f4DIJhAEsMN:bxo4a7e) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/3d543219d6f9e362786ba1fc741177e0e9461a19/Makefile#L39)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm not sure how to combine env setting `CGO_ENABLED=0` & `@` in a single command
if you guys are aware LMK

If no i'm ok to keep it like this
</blockquote></details>

That expression seems good.

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/37)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/37)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @miladz68, and @ysv)

___
*[`Makefile` line 94 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/37#-Nj7U_oF5DAFRQ9VodWW:-Nj7U_oGDeEAfg2MmhrH:b-yigpbu) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/3d543219d6f9e362786ba1fc741177e0e9461a19/Makefile#L94)):*
> ```Makefile
> clean:
> 	rm -f tools-stamp ./build/**
> .PHONY: clean
> ```

new line at the end

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/37)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @wojtek-coreum)

___
*[`Makefile` line 94 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/37#-Nj7U_oF5DAFRQ9VodWW:-Nj7hPVF1p8S90gWyx8E:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/3d543219d6f9e362786ba1fc741177e0e9461a19/Makefile#L94)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

new line at the end
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/37)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu and @miladz68)

**Pull request merged**
