### PR TITLE
Upgrade Cosmos SDK to v0.47.5

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/34)

### CODE REVIEW

**Review by ysv — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @keyleu, and @miladz68)

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu and @miladz68)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/34)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/bdjuno/34#-NirxwtX6_s-EuFvm84l:-NirxwtX6_s-EuFvm84m:b-mnh840) (no related file):*
https://github.com/CoreumFoundation/bdjuno/actions/runs/6810486361/job/18518866566?pr=34
Build is failed and it was failed before BTW>

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/34)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/bdjuno/34#-NirxwtX6_s-EuFvm84l:-NisOuvf8GqBGkhKUm6C:b-896fix) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

https://github.com/CoreumFoundation/bdjuno/actions/runs/6810486361/job/18518866566?pr=34
Build is failed and it was failed before BTW>
</blockquote></details>

Done.

___

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/34)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, and @wojtek-coreum)

___
*[`.github/workflows/test.yml` line 42 at r5](https://reviewable.io/reviews/CoreumFoundation/bdjuno/34#-NismOFV2UbFrR5yz3Ab:-NismOFV2UbFrR5yz3Ac:b8sznmn) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/7344c58bca37c951230f402eb4341b1f9282be07/.github/workflows/test.yml#L42)):*
> ```YAML
>             .sum
> 
>       - name: Build 🔨
> ```

do we really need to remove this step ?

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/34)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/34)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @ysv)

___
*[`.github/workflows/test.yml` line 42 at r5](https://reviewable.io/reviews/CoreumFoundation/bdjuno/34#-NismOFV2UbFrR5yz3Ab:-Nit-cgf0JKdKhWQBFz4:b-7d6cwf) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/7344c58bca37c951230f402eb4341b1f9282be07/.github/workflows/test.yml#L42)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we really need to remove this step ?
</blockquote></details>

We might put it back once bdjuno compiles without cgo

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu and @miladz68)

**Pull request merged**
