### PR TITLE
Build binary on the runner and add to docker image

### PR DESCRIPTION
**Pull request by alinetskyi**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/72)

### CODE REVIEW

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/72)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/72)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alinetskyi, @miladz68, and @ysv)

___
*[`Dockerfile` line 5 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/72#-O0hCkj58wlwv26-8lx5:-O0hCkj6DMtNUzh7VsB4:b35y6gm) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/86c4ac78114a9959be908332ed11521f5d63dbac/Dockerfile#L5)):*
> ```Dockerfile
> RUN apk update
> RUN apk add postgresql
> COPY ./bin/.cache/bdjuno/docker.linux.amd64/bin/bdjuno /usr/bin/bdjuno
> ```

Why do you copy the `amd64` if the build can be for  `linux/amd64,linux/arm64  architectures?

**Review by alinetskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/72)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`Dockerfile` line 5 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/72#-O0hCkj58wlwv26-8lx5:-O0iCsUIEScIWyf4Fc9R:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/86c4ac78114a9959be908332ed11521f5d63dbac/Dockerfile#L5)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you copy the `amd64` if the build can be for  `linux/amd64,linux/arm64  architectures?
</blockquote></details>

Done.

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/72)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/72)* status: all files reviewed, 1 unresolved discussion (waiting on @alinetskyi and @ysv)

___
*[`Dockerfile` line 5 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/72#-O0hCkj58wlwv26-8lx5:-O0nMSUwABC1tFu6KwAg:b-l7p19j) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/86c4ac78114a9959be908332ed11521f5d63dbac/Dockerfile#L5)):*
<details><summary><i>Previously, alinetskyi (Artem Linetskiy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually we need both

**Review by alinetskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/72)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`Dockerfile` line 5 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/72#-O0hCkj58wlwv26-8lx5:-O0pCox7E0qQ_U3TglTJ:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/86c4ac78114a9959be908332ed11521f5d63dbac/Dockerfile#L5)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually we need both
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/72)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/72)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
