### PR TITLE
Add assetft, assetnft, nft, wasm account parsers and wasm event accont parser.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/27)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/27)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

___
*[`modules/wasm/handle_msg.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/27#-NbO-pZ01_227WKBztMX:-NbO-pZ01_227WKBztMY:bm1fqot) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/e97270cab5c54341a7008934d962d479cf9e6bbb/modules/wasm/handle_msg.go#L32)):*
> ```Go
> 
> func (m *Module) handleWasmRelatedAddress(index int, msg sdk.Msg, tx *juno.Tx) error {
> 	eventsAddresses := m.findBech32EventValues(tx.Events)
> ```

`eventAddresses`
___
*[`modules/wasm/handle_msg.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/27#-NbO01akAmhdPpqYyDpM:-NbO01akAmhdPpqYyDpN:b70aqoi) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/e97270cab5c54341a7008934d962d479cf9e6bbb/modules/wasm/handle_msg.go#L44)):*
> ```Go
> 
> 	// we join and then do the Uniq since the receivers might be duplicated
> 	addresses = lo.Uniq(append(addresses, eventsAddresses...))
> ```

Instead of filtering out duplicated addresses, it would be better to avoid adding them initially

**Review by miladz68 — DISMISSED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/27)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @vertex451, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/27)* status: all files reviewed, 2 unresolved discussions (waiting on @vertex451, @wojtek-coreum, and @ysv)

___
*[`modules/wasm/handle_msg.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/27#-NbO-pZ01_227WKBztMX:-NbOlBzfBOhtHy7NfUSM:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/e97270cab5c54341a7008934d962d479cf9e6bbb/modules/wasm/handle_msg.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`eventAddresses`
</blockquote></details>

Done.
___
*[`modules/wasm/handle_msg.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/27#-NbO01akAmhdPpqYyDpM:-NbOk7cD2V2G316UbLu_:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/e97270cab5c54341a7008934d962d479cf9e6bbb/modules/wasm/handle_msg.go#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Instead of filtering out duplicated addresses, it would be better to avoid adding them initially
</blockquote></details>

Done.

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @ysv)

**Pull request merged**
