### PR TITLE
feat: Integrate the bgjuno with the coreum chain

### PR DESCRIPTION
**Pull request by dzmitryhil**
## Description

* Integrate the corem instead of gaja
* Add hasura Dockerfile
* Add docker-compose to run full back-end
* Add bdjuno config-sample.yaml
* Add launch instructions

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/1)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/1)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @alinetskyi, @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`docker-compose.yml` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDXMOVd2rbf0v7zHODU:-NDXMOVd2rbf0v7zHODV:be7qt9o) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/b8edfd896f8f3c1a4416591a8f51d2c6c88d216f/docker-compose.yml#L28)):*
> ```YAML
>       dockerfile: Dockerfile
>       args:
>         arch: x86_64 # update to aarch64 if you want to use that arch
> ```

@alinetskyi 
Here we use the "x86_64" and its default in the docker file, if you want to build with the support of the just change that param.
___
*[`docker-compose.yml` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDXM19f0Du1GquWArEo:-NDXM19g1r1DzdYa2jrv:bg4s2kf) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/b8edfd896f8f3c1a4416591a8f51d2c6c88d216f/docker-compose.yml#L58)):*
> ```YAML
>       ## uncomment next line to set an admin secret
>       HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
>       HASURA_GRAPHQL_METADATA_DIR: /hasura/metadata
> ```

The "HASURA_GRAPHQL_METADATA_DIR" is required to import the metadata from the images
The "ACTION_BASE_URL" is used to proxy some requests to the "bdjuno" and the "bdjuno" will proxy it to the cored node.



_Code quote:_
```YAML
HASURA_GRAPHQL_METADATA_DIR
```
___
*[`README.md` line 39 at r1](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDXLa26AbQH_948Xdkx:-NDXLa26AbQH_948Xdky:bbyz0xr) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/b8edfd896f8f3c1a4416591a8f51d2c6c88d216f/README.md#L39)):*
> ```Markdown
> ## Local launch in docker compose
> 
> * Create .bdjuno folder and copy config.toml (based on config-sample.yaml) and genesis.json of your chain.
> ```

@alinetskyi Is it clear here?



_Code quote:_
```Markdown
In case you run the bdjuno with 
```

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/1)* status: all files reviewed, 7 unresolved discussions (waiting on @alinetskyi, @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`docker-compose.yml` line 4 at r2](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDXNcHB854RC2QeXeAq:-NDXNcHB854RC2QeXeAr:bvwbo2r) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/2bea265d872273f9150540a543699147501c06c0/docker-compose.yml#L4)):*
> ```YAML
> services:
>   postgres:
>     image: postgres:latest
> ```

It is bettter to have fixed version instead of latest
___
*[`docker-compose.yml` line 40 at r2](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDXNoGC1ZZCNmtsbuPV:-NDXNoGC1ZZCNmtsbuPW:bx5qvgx) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/2bea265d872273f9150540a543699147501c06c0/docker-compose.yml#L40)):*
> ```YAML
>     build:
>       context: .
>       dockerfile: hasura.Dockerfile
> ```

minor isn't it common practice to name it `Dockerfile.{smth}` (e.g Dockerfile.hasura) ?
___
*[`README.md` line 39 at r2](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDXei4b3cppg9Oeo8mI:-NDXei4b3cppg9Oeo8mJ:bx4l9wl) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/2bea265d872273f9150540a543699147501c06c0/README.md#L39)):*
> ```Markdown
> ## Local launch in docker compose
> 
> * Create .bdjuno folder and copy config.toml (based on config-sample.yaml) and genesis.json of your chain.
> ```

-> `Create .bdjuno folder and inside it create config.toml (for sample of config check config-sample.yaml) and genesis.json of your chain.`
___
*[`README.md` line 48 at r2](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDXf4NuAMbDVKrcKNRR:-NDXf4NuAMbDVKrcKNRS:byawi61) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/2bea265d872273f9150540a543699147501c06c0/README.md#L48)):*
> ```Markdown
> 
> * Open [hasura UI](http://localhost:8080/console) and check that it works correctly.
> The default password is the docker-compose.yaml file and is: "myadminsecretkey"
> ```

The password is defined in docker-compose.yaml and set to "myadminsecretkey" by default.



_Code quote:_
```Markdown
The default password is the docker-compose.yaml file and is: "myadminsecretkey"
```

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/1)* status: all files reviewed, 7 unresolved discussions (waiting on @alinetskyi, @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`docker-compose.yml` line 4 at r2](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDXNcHB854RC2QeXeAq:-NDXgRxB0W2AhCDTikp7:bn8167m) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/2bea265d872273f9150540a543699147501c06c0/docker-compose.yml#L4)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

It is bettter to have fixed version instead of latest
</blockquote></details>

Agree, updated. 
___
*[`docker-compose.yml` line 40 at r2](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDXNoGC1ZZCNmtsbuPV:-NDXgyRMAri4D6LkN057:b-8ezbo2) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/2bea265d872273f9150540a543699147501c06c0/docker-compose.yml#L40)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor isn't it common practice to name it `Dockerfile.{smth}` (e.g Dockerfile.hasura) ?
</blockquote></details>

Agree, updated.
___
*[`README.md` line 39 at r2](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDXei4b3cppg9Oeo8mI:-NDXh7gcDEES07ahm3cE:b-896fix) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/2bea265d872273f9150540a543699147501c06c0/README.md#L39)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

-> `Create .bdjuno folder and inside it create config.toml (for sample of config check config-sample.yaml) and genesis.json of your chain.`
</blockquote></details>

Done.
___
*[`README.md` line 48 at r2](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDXf4NuAMbDVKrcKNRR:-NDXhDjd5s2cyrgKHdIe:b-896fix) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/2bea265d872273f9150540a543699147501c06c0/README.md#L48)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

The password is defined in docker-compose.yaml and set to "myadminsecretkey" by default.
</blockquote></details>

Done.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/1)* status: 5 of 13 files reviewed, 8 unresolved discussions (waiting on @alinetskyi, @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`database/schema/setup.sh` line 0 at r9](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDY_ZINAhg8wwcacrgz:-NDY_ZINAhg8wwcacrh-:bkd5hip) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/27d833110e8d15d330f6808ba7cab3b612915e54/database/schema/setup.sh#L0)):*
@alinetskyi pay attention plz
I removed that file since it broked the unit (integration) tests.

**Review by alinetskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/1)* status: 5 of 18 files reviewed, 8 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`database/schema/setup.sh` line  at r9](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDY_ZINAhg8wwcacrgz:-NDbZfzN8Jw6CH9EDXbX:b-1gstfe) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/27d833110e8d15d330f6808ba7cab3b612915e54/database/schema/setup.sh#L)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@alinetskyi pay attention plz
I removed that file since it broked the unit (integration) tests.
</blockquote></details>

how to do suggest we run migations?

**Review by alinetskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/1)* status: 5 of 18 files reviewed, 8 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`docker-compose.yml` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDXMOVd2rbf0v7zHODU:-NDbZoxn8HUAmch5rJ0Z:b-mx77kz) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/b8edfd896f8f3c1a4416591a8f51d2c6c88d216f/docker-compose.yml#L28)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@alinetskyi 
Here we use the "x86_64" and its default in the docker file, if you want to build with the support of the just change that param.
</blockquote></details>

noted
___
*[`README.md` line 39 at r1](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDXLa26AbQH_948Xdkx:-NDbZrzZ9-Oe2svS2HTZ:b2nih0v) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/b8edfd896f8f3c1a4416591a8f51d2c6c88d216f/README.md#L39)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@alinetskyi Is it clear here?
</blockquote></details>

yup

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/1)* status: 5 of 18 files reviewed, 6 unresolved discussions (waiting on @alinetskyi, @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`database/schema/setup.sh` line  at r9](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDY_ZINAhg8wwcacrgz:-NDc3zdTCuh160VtWYxv:bv3ukv5) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/27d833110e8d15d330f6808ba7cab3b612915e54/database/schema/setup.sh#L)):*
<details><summary><i>Previously, alinetskyi (Artem Linetskiy) wrote…</i></summary><blockquote>

how to do suggest we run migations? 
</blockquote></details>

You can have this script but not in that folder or you run them using the snippet:
```
SCRIPTS="/path/to/your/directory"
for file in $SCRIPTS/*; do
    psql <insert your options here> "${file}"
done
``` 
Since the scripts are named with the index prefix they will be executed in the proper order

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, 1 of 3 files at r7, 1 of 2 files at r8, 1 of 1 files at r10, 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/1)* status: all files reviewed, 3 unresolved discussions (waiting on @alinetskyi, @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`docker-compose.yml` line 35 at r11](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDcFUEWDVtc5JON8a_A:-NDcFUEX5mPzTRm1CyAK:bkkkakm) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/b0bff74d7cc02957db82ab5aa66ec604c0ea1491/docker-compose.yml#L35)):*
> ```YAML
>     command: bdjuno start --home /bdjuno/.bdjuno
>     volumes:
>       - .bdjuno:/bdjuno/.bdjuno
> ```

Is the folder named .bdjuno is also used in original bdjuno repo ?

Because I don't like to have dot folders related to original repo. It is ok to have .github, .git because they are third party tools and we sort of hide them but this folder is related to this component
I personally would name it `./config` and put there config-sample.toml & genesis-sample.json (optional)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/1)* status: all files reviewed, 3 unresolved discussions (waiting on @alinetskyi, @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`docker-compose.yml` line 35 at r11](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDcFUEWDVtc5JON8a_A:-NDcGNmTDCzzMZDUIWwa:b-bkhgle) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/b0bff74d7cc02957db82ab5aa66ec604c0ea1491/docker-compose.yml#L35)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Is the folder named .bdjuno is also used in original bdjuno repo ?

Because I don't like to have dot folders related to original repo. It is ok to have .github, .git because they are third party tools and we sort of hide them but this folder is related to this component
I personally would name it `./config` and put there config-sample.toml & genesis-sample.json (optional)
</blockquote></details>

In this way it is easier for users to understand the structure of folder, nothing extra needs to be created etc

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/1)* status: all files reviewed, 3 unresolved discussions (waiting on @alinetskyi, @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`docker-compose.yml` line 35 at r11](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDcFUEWDVtc5JON8a_A:-NDcHDRdAcyM2tGZEviD:b-s9v6be) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/b0bff74d7cc02957db82ab5aa66ec604c0ea1491/docker-compose.yml#L35)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

In this way it is easier for users to understand the structure of folder, nothing extra needs to be created etc
</blockquote></details>

Yes, it's the default name from the tutorial:

https://docs.bigdipper.live/cosmos-based/parser/setup

We can change it, but as for me, the ".config" looks similar to ".bdjuno"

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/bdjuno/1)* status: all files reviewed, 2 unresolved discussions (waiting on @alinetskyi, @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`docker-compose.yml` line 35 at r11](https://reviewable.io/reviews/coreumfoundation/bdjuno/1#-NDcFUEWDVtc5JON8a_A:-NDdJrk_7xW9W--Jcspy:b-5yivte) ([raw file](https://github.com/coreumfoundation/bdjuno/blob/b0bff74d7cc02957db82ab5aa66ec604c0ea1491/docker-compose.yml#L35)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes, it's the default name from the tutorial:

https://docs.bigdipper.live/cosmos-based/parser/setup

We can change it, but as for me, the ".config" looks similar to ".bdjuno"
</blockquote></details>

I meant to name folder just `config`
But ok if it is what they suggest in their doc then lets use it

**Pull request merged**
