### PR TITLE
Also add url to sample config & fix schema

### PR DESCRIPTION
**Pull request by alinetskyi**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/33)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/33)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alinetskyi, @keyleu, @miladz68, and @ysv)

___
*[`config-sample.yaml` line 43 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/33#-NidOZfx-XLszJ7kIEdU:-NidOZfx-XLszJ7kIEdV:b-k3h1zw) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/0835b9cebf58b392fb6f3118592cf791398b0f49/config-sample.yaml#L43)):*
> ```YAML
> database:
>     url: postgresql://root:password@postgres:5432/root?sslmode=disable&search_path=public
>     name: root # This is the defaults, but might be updated
> ```

Why do need other args you use the URL ?

**Review by alinetskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/33)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @miladz68, and @ysv)

___
*[`config-sample.yaml` line 43 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/33#-NidOZfx-XLszJ7kIEdU:-Nid_WJp3BX-jsbV6XSM:b3qcvc9) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/0835b9cebf58b392fb6f3118592cf791398b0f49/config-sample.yaml#L43)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do need other args you use the URL ?
</blockquote></details>

this will allow to support both versions of bdjuno new and old

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/33)* status: all files reviewed, 2 unresolved discussions (waiting on @alinetskyi, @dzmitryhil, @keyleu, and @miladz68)

___
*[`database/schema/02-bank.sql` line 11 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/33#-Nidcif37ml8DhQpH_tJ:-Nidcif37ml8DhQpH_tK:bfccaw3) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/6e299e9dd1c9f37d3d98bb218ead90c3e5de3304/database/schema/02-bank.sql#L11)):*
> ```TSQL
> );
> CREATE INDEX staking_params_height_index ON staking_params (height);
> ```

it is a bad idea to modify existing migration

**Review by alinetskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/33)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, and @ysv)

___
*[`database/schema/02-bank.sql` line 11 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/33#-Nidcif37ml8DhQpH_tJ:-NidfzEd-jD3tpPwlaY5:bkr0yid) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/6e299e9dd1c9f37d3d98bb218ead90c3e5de3304/database/schema/02-bank.sql#L11)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

it is a bad idea to modify existing migration
</blockquote></details>

Well, it was modified in wojtek's PR, I just revert it back here to how it's supposed to be

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/33)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/33)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @ysv)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/33)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu and @miladz68)

**Pull request merged**
