### PR TITLE
Extract addresses from all transactions and events

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @miladz68, and @wojtek-coreum)

___
*[`modules/group/account_parser.go` line 28 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39#-NjI-7903VFFVpgKoom1:-NjI-7903VFFVpgKoom2:bw7507f) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/62a1b7f1e2b2b5b71df3f5bdaec3f0341ecffc2a/modules/group/account_parser.go#L28)):*
> ```Go
> 		return addresses, nil
> 	case *group.MsgSubmitProposal:
> 		return []string{msg.GroupPolicyAddress}, nil
> ```

if we create a message inside the proposal e.g bank send and it has recipient
Will this tx be displayed on dest address also ? How does this work for authz.Exec ?  I guess it will be the same here

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @wojtek-coreum)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu and @ysv)

___
*[`modules/group/account_parser.go` line 28 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39#-NjI-7903VFFVpgKoom1:-NjN1cpI49FfXiV-U4f7:b-15t5fa) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/62a1b7f1e2b2b5b71df3f5bdaec3f0341ecffc2a/modules/group/account_parser.go#L28)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

if we create a message inside the proposal e.g bank send and it has recipient
Will this tx be displayed on dest address also ? How does this work for authz.Exec ?  I guess it will be the same here
</blockquote></details>

Authz is handled by juno: https://github.com/forbole/juno/blob/v5.2.0/modules/messages/account_parser.go#L268
It supports built-in messages, but those created by us are not handled by default. We would have to fork juno and add our messages there or do it inside bdjuno.

Do we want to copy this logic and use it for groups? We might also wait until groups are supported natively, but then again - our custom messages won't be parsed.

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu and @wojtek-coreum)

___
*[`modules/group/account_parser.go` line 28 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39#-NjI-7903VFFVpgKoom1:-NjNx4zQAE_zeTTw0kyB:b-vwkk77) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/62a1b7f1e2b2b5b71df3f5bdaec3f0341ecffc2a/modules/group/account_parser.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Authz is handled by juno: https://github.com/forbole/juno/blob/v5.2.0/modules/messages/account_parser.go#L268
It supports built-in messages, but those created by us are not handled by default. We would have to fork juno and add our messages there or do it inside bdjuno.

Do we want to copy this logic and use it for groups? We might also wait until groups are supported natively, but then again - our custom messages won't be parsed.
</blockquote></details>

As we agreed on call lets have a single parser for all messages which goes through all events and fetches all address correct in terms of regexp and add them.
By the way as for regexp - maybe we can even improve it and try to use smth like `sdk.ParseAccAddress` ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @miladz68, and @ysv)

___
*[`modules/group/account_parser.go` line 28 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39#-NjI-7903VFFVpgKoom1:-NjRxS_xEdDVOk7rzY7H:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/62a1b7f1e2b2b5b71df3f5bdaec3f0341ecffc2a/modules/group/account_parser.go#L28)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

As we agreed on call lets have a single parser for all messages which goes through all events and fetches all address correct in terms of regexp and add them.
By the way as for regexp - maybe we can even improve it and try to use smth like `sdk.ParseAccAddress` ?
</blockquote></details>

Done.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu and @wojtek-coreum)

___
*[`modules/group/handle_msg.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39#-NjS6K9N85q0I-kBVPpb:-NjS6K9N85q0I-kBVPpc:b-shblj0) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/3ede61ff90734c27c8866aa318a3775f9ab3cf1c/modules/group/handle_msg.go#L17)):*
> ```Go
> 
> 	switch cosmosMsg := msg.(type) {
> 	case *group.MsgExec,
> ```

as far as I understood from our discussion we decided to do this for literally all messges of cosmos sdk

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @keyleu and @ysv)

___
*[`modules/group/handle_msg.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39#-NjS6K9N85q0I-kBVPpb:-Njfu36D7JGkLVIuNgNc:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/3ede61ff90734c27c8866aa318a3775f9ab3cf1c/modules/group/handle_msg.go#L17)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

as far as I understood from our discussion we decided to do this for literally all messges of cosmos sdk
</blockquote></details>

Done.

**Review by ysv — DISMISSED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu and @wojtek-coreum)

___
*[`modules/group/account_parser.go` line 3 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39#-NjgK6747k_urJPmcODt:-NjgK6747k_urJPmcODu:bllph4v) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1f9541c8168554f347d546dd13628612c373da33/modules/group/account_parser.go#L3)):*
> ```Go
> package group
> 
> import (
> ```

Why do you need the `group` and other addresses parsers if you have one which parses everything?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @keyleu)

___
*[`modules/group/account_parser.go` line 3 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39#-NjgK6747k_urJPmcODt:-NjgLhHmDUDUr6gzDgqQ:bdognpr) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1f9541c8168554f347d546dd13628612c373da33/modules/group/account_parser.go#L3)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need the `group` and other addresses parsers if you have one which parses everything?
</blockquote></details>

Because events might not covering everything. For example when group is created there is no event enumerating members.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu and @wojtek-coreum)

___
*[`modules/group/account_parser.go` line 3 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39#-NjgK6747k_urJPmcODt:-NjgV4bG778FOkMNpvdV:b-slm56q) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1f9541c8168554f347d546dd13628612c373da33/modules/group/account_parser.go#L3)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Because events might not covering everything. For example when group is created there is no event enumerating members.
</blockquote></details>

Right, that's why we should decode the message to JSON string, and use the same pattern as in events. So we won't need to update the message parsers for new messages as well.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @miladz68, and @ysv)

___
*[`modules/group/account_parser.go` line 3 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39#-NjgK6747k_urJPmcODt:-NjkzqQh61VDWBvwunAp:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1f9541c8168554f347d546dd13628612c373da33/modules/group/account_parser.go#L3)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Right, that's why we should decode the message to JSON string, and use the same pattern as in events. So we won't need to update the message parsers for new messages as well.
</blockquote></details>

Done.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

___
*[`cmd/bdjuno/main.go` line 72 at r4](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39#-NjlnnML8dvOIt1lMYKl:-NjlnnML8dvOIt1lMYKm:bc9h0zk) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/f5810d95e898fda8c3af2418d6108bfd0ac0c262/cmd/bdjuno/main.go#L72)):*
> ```Go
> 		assetft.MessagesParser,
> 		assetnft.MessagesParser,
> 		nft.MessagesParser,
> ```

Why do you still need those message parsers? Isn't it enough to have just one new?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)* status: 5 of 12 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @miladz68, and @ysv)

___
*[`cmd/bdjuno/main.go` line 72 at r4](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39#-NjlnnML8dvOIt1lMYKl:-NjlzoN09V8yfQ6ZbXIA:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/f5810d95e898fda8c3af2418d6108bfd0ac0c262/cmd/bdjuno/main.go#L72)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you still need those message parsers? Isn't it enough to have just one new?
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)* status: 5 of 12 files reviewed, all discussions resolved (waiting on @keyleu, @miladz68, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 3 of 4 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/39)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu and @miladz68)

**Pull request merged**
