### PR TITLE
Update validator statuses during parsing

### PR DESCRIPTION
**Pull request by alinetskyi**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @alinetskyi, @miladz68, @wojtek-coreum, and @ysv)

___
*[`modules/staking/utils_validators.go` line 85 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50#-NoQhd340br-uJOCWH_w:-NoQhd340br-uJOCWH_x:bo0ajvh) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/4bf17a03d97fd82614ba7c68ee60f87d0864f458/modules/staking/utils_validators.go#L85)):*
> ```Go
> func (m *Module) RefreshAllValidatorInfos(height int64) error {
> 	// Get all validators
> 	validators, err := m.db.GetValidators()
> ```

You need to join the validator at the height and from the DB (the height data ), since if there are more validators at the height you will miss them. 
___
*[`modules/staking/utils_validators.go` line 112 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50#-NoQiZ8_0JYkBlERFdGM:-NoQiZ8_0JYkBlERFdGN:b-k563ee) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/4bf17a03d97fd82614ba7c68ee60f87d0864f458/modules/staking/utils_validators.go#L112)):*
> ```Go
> 			}
> 
> 			err = m.db.SaveValidatorsStatuses([]types.ValidatorStatus{types.NewValidatorStatus(validator.GetConsAddr(), validator.GetConsPubKey(), 1, true, height)})
> ```

It would be nice to have a constant for the status since it is unclear what the `1` means.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @alinetskyi, @miladz68, @wojtek-coreum, and @ysv)

___
*[`modules/staking/utils_validators.go` line 85 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50#-NoQhd340br-uJOCWH_w:-NoQj1Ps9zAzZN6ioyl3:b-k4bcxz) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/4bf17a03d97fd82614ba7c68ee60f87d0864f458/modules/staking/utils_validators.go#L85)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You need to join the validator at the height and from the DB (the height data ), since if there are more validators at the height you will miss them.
</blockquote></details>

The height data is with the higher priority

**Review by alinetskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`modules/staking/utils_validators.go` line 85 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50#-NoQhd340br-uJOCWH_w:-NoWlVqZ8z5N-q56wGU8:b-rm8c1t) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/4bf17a03d97fd82614ba7c68ee60f87d0864f458/modules/staking/utils_validators.go#L85)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The height data is with the higher priority
</blockquote></details>

technically, any new validators will be picked up by either block processing or the cronjob that refreshes the validator, but yeah I agree with this for the most part

**Review by alinetskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`modules/staking/utils_validators.go` line 112 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50#-NoQiZ8_0JYkBlERFdGM:-NoWmD286GzPmsVXM_ie:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/4bf17a03d97fd82614ba7c68ee60f87d0864f458/modules/staking/utils_validators.go#L112)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It would be nice to have a constant for the status since it is unclear what the `1` means.
</blockquote></details>

Done.

**Review by alinetskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`modules/staking/utils_validators.go` line 85 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50#-NoQhd340br-uJOCWH_w:-NoXJvjl8x3b4bFThLZo:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/4bf17a03d97fd82614ba7c68ee60f87d0864f458/modules/staking/utils_validators.go#L85)):*
<details><summary><i>Previously, alinetskyi (Artem Linetskiy) wrote…</i></summary><blockquote>

technically, any new validators will be picked up by either block processing or the cronjob that refreshes the validator, but yeah I agree with this for the most part
</blockquote></details>

Done.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`modules/staking/utils_validators.go` line 96 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50#-Nojml4A8lyFCxAKt_Hi:-Nojml4A8lyFCxAKt_Hj:by6e49i) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/ed0fad5047e8cdf79bd330f4ba94d8903f183eb5/modules/staking/utils_validators.go#L96)):*
> ```Go
> 
> 	// Merge validatorsFromDb and validatorsFromHeight arrays
> 	validators := make([]types.Validator, 0, len(validatorsFromDb)+len(validatorsFromHeight))
> ```

nit: Better to remove the `len(validatorsFromDb)+len(validatorsFromHeight)` since that value is not the final length of the slice.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`modules/staking/utils_validators.go` line 96 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50#-Nol7MBCANjL0wNYJPyH:-Nol7MBD8-8pL5UWG4E-:b-ixn3qn) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/c7251e72d2638d912f80f8cc06abe9b8df72a8e9/modules/staking/utils_validators.go#L96)):*
> ```Go
> 
> 	// Merge validatorsFromDb and validatorsFromHeight arrays
> 	validators := make([]types.Validator, 0, len(validatorsFromDb))
> ```

`make([]types.Validator, 0, len(validatorsFromDb))` -> `make([]types.Validator, 0)`



_Code quote:_
```Go
, len(validatorsFromDb))
```

**Review by alinetskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`modules/staking/utils_validators.go` line 96 at r2](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50#-Nojml4A8lyFCxAKt_Hi:-Nol8FfRA6k3CAszfJxy:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/ed0fad5047e8cdf79bd330f4ba94d8903f183eb5/modules/staking/utils_validators.go#L96)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

nit: Better to remove the `len(validatorsFromDb)+len(validatorsFromHeight)` since that value is not the final length of the slice.
</blockquote></details>

Done.
___
*[`modules/staking/utils_validators.go` line 96 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50#-Nol7MBCANjL0wNYJPyH:-Nol8Gqh7xPzLFY5a2gd:b-s2yt74) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/c7251e72d2638d912f80f8cc06abe9b8df72a8e9/modules/staking/utils_validators.go#L96)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`make([]types.Validator, 0, len(validatorsFromDb))` -> `make([]types.Validator, 0)`
</blockquote></details>

Yeah, but this array will definetly be at least of the size of validatorsFromDb

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`modules/staking/utils_validators.go` line 96 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50#-Nol7MBCANjL0wNYJPyH:-NomtuLm3Mq78KifzL05:blpskwt) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/c7251e72d2638d912f80f8cc06abe9b8df72a8e9/modules/staking/utils_validators.go#L96)):*
<details><summary><i>Previously, alinetskyi (Artem Linetskiy) wrote…</i></summary><blockquote>

Yeah, but this array will definetly be at least of the size of validatorsFromDb
</blockquote></details>

We usually don't care about such things, but I think Artem is right. 
In terms of memory re-allocation his implementation is more optimal I think

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

___
*[`modules/staking/utils_validators.go` line 96 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50#-Nol7MBCANjL0wNYJPyH:-Noowxpi6vE2wZxUR8NY:bmp4y5u) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/c7251e72d2638d912f80f8cc06abe9b8df72a8e9/modules/staking/utils_validators.go#L96)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

We usually don't care about such things, but I think Artem is right. 
In terms of memory re-allocation his implementation is more optimal I think
</blockquote></details>

So you can reallocate anyways, or allocate redundant. in that case, it's better to do with default IMO.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/50)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Pull request merged**
