### PR TITLE
feat: remove height usage in action handlers

### PR DESCRIPTION
**Pull request by akhlopiachyi**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/66)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/66)* status: 0 of 26 files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/bdjuno/66#-Nw4_Gvq99JNAu45z4Dp:-Nw4_Gvq99JNAu45z4Dq:bsz78ec) (no related file):*
Could you please explain the problem you are solving ?

___

**Review by miladz68 — APPROVED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/66)* status: all files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi, @wojtek-coreum, and @ysv)

**Comment by akhlopiachyi** [comment]
PR is frizzed for 2 weeks
If the bug will not be reproduced anymore, PR will be closed

**Comment by akhlopiachyi** [comment]
Closed because the bug was not reproduced for few weeks

**Pull request closed without merging**
