### PR TITLE
CI workflow

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/65)

### CODE REVIEW

**Review by miladz68 — DISMISSED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/65)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @keyleu, and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/65)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @keyleu and @ysv)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/65)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @keyleu and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/65)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @keyleu and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/65)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu and @wojtek-coreum)

___
*[`build/bdjuno/build.go` line 45 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/65#-NwdU84P2u5_8uH9g48I:-NwdU84Q6Wo_ls8ak1Iy:b-i1bao6) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/74ec943f64cde0c45de19d9636e250480eec9685/build/bdjuno/build.go#L45)):*
> ```Go
> 		PackagePath:    filepath.Join(repoPath, "cmd", "bdjuno"),
> 		Flags: []string{
> 			binaryOutputFlag + "=" + binOutputPath,
> ```

I think we rolled back to BinOutput as a standalone attribute
Lets update it here

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/65)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @ysv)

___
*[`build/bdjuno/build.go` line 45 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/65#-NwdU84P2u5_8uH9g48I:-NwdVCzTCJAltxNWJa6w:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/74ec943f64cde0c45de19d9636e250480eec9685/build/bdjuno/build.go#L45)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think we rolled back to BinOutput as a standalone attribute
Lets update it here
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/65)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/65)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @keyleu and @miladz68)

**Pull request merged**
