### PR TITLE
Use latest height for the proposals state for the re-indexing if height state is missing.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, and @wojtek-coreum)

___
*[`modules/gov/handle_msg.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41#-NkGSfux7Ac98JAPLfYw:-NkGSfux7Ac98JAPLfYx:b-oka159) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/e17ba2b61d5f02bb2c56b18d23e073efb3e1e7fb/modules/gov/handle_msg.go#L58)):*
> ```Go
> 	}
> 
> 	// Get the proposal
> ```

confusing comment location now, or ok ?
___
*[`modules/gov/handle_msg.go` line 163 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41#-NkGT3Zr063rVjFd-xl6:-NkGT3Zr063rVjFd-xl7:b-z4rprm) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/e17ba2b61d5f02bb2c56b18d23e073efb3e1e7fb/modules/gov/handle_msg.go#L163)):*
> ```Go
> 		return targetHeight, nil
> 	}
> 	if strings.Contains(err.Error(), "version mismatch on immutable IAVL tree") {
> ```

what does this error mean ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

___
*[`modules/gov/handle_msg.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41#-NkGSfux7Ac98JAPLfYw:-NkJI4sHBlRe35A2ct_u:b1u0ziq) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/e17ba2b61d5f02bb2c56b18d23e073efb3e1e7fb/modules/gov/handle_msg.go#L58)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

confusing comment location now, or ok ?
</blockquote></details>

Reminded from the prev code, removed. 
___
*[`modules/gov/handle_msg.go` line 163 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41#-NkGT3Zr063rVjFd-xl6:-NkJI87CCS-kLAKGK70u:b-113ekk) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/e17ba2b61d5f02bb2c56b18d23e073efb3e1e7fb/modules/gov/handle_msg.go#L163)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what does this error mean ?
</blockquote></details>

We get that error if we don't have the state for the height.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @miladz68, and @wojtek-coreum)

___
*[`modules/gov/handle_msg.go` line 163 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41#-NkGT3Zr063rVjFd-xl6:-NkKiFp0-7K1KY7oZ1C8:b-gcokjg) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/e17ba2b61d5f02bb2c56b18d23e073efb3e1e7fb/modules/gov/handle_msg.go#L163)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We get that error if we don't have the state for the height.
</blockquote></details>

could you pls add comment so it is clear for future

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

___
*[`modules/gov/handle_msg.go` line 163 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41#-NkGT3Zr063rVjFd-xl6:-NkPQ8A17Yi4NSK5RYqS:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/e17ba2b61d5f02bb2c56b18d23e073efb3e1e7fb/modules/gov/handle_msg.go#L163)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

could you pls add comment so it is clear for future
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu, @miladz68, and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, and @miladz68)

___
*[`modules/gov/handle_msg.go` line 165 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41#-NkQ2_oHDr2TSn_8_EvU:-NkQ2_oIAbpJPEfvAFWQ:b-kmg30w) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/cda783ccc28ee88da07d2a02b5b456828c97b31f/modules/gov/handle_msg.go#L165)):*
> ```Go
> 	if strings.Contains(err.Error(), "version mismatch on immutable IAVL tree") {
> 		// zero is equal to latest in terms of the client
> 		return 0, nil
> ```

But it will produce inaccurate result in the explorer

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @wojtek-coreum)

___
*[`modules/gov/handle_msg.go` line 165 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41#-NkQ2_oHDr2TSn_8_EvU:-NkQ8j332mDuWKBVdp31:bjj804y) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/cda783ccc28ee88da07d2a02b5b456828c97b31f/modules/gov/handle_msg.go#L165)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But it will produce inaccurate result in the explorer
</blockquote></details>

Actually - not.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, and @miladz68)

___
*[`modules/gov/handle_msg.go` line 165 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41#-NkQ2_oHDr2TSn_8_EvU:-NkQEC_O4kP5lRuVIsyB:b-kwl9fo) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/cda783ccc28ee88da07d2a02b5b456828c97b31f/modules/gov/handle_msg.go#L165)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually - not.
</blockquote></details>

no? What if the height is different than the one when tx was executed?

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil and @keyleu)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41#-NkQGisd7zWiVddK7Yuq:-NkQGisd7zWiVddK7Yur:bz0hus6) (no related file):*
The PR is made agains `chains/coreum` branch which contains v0.47 cosmos sdk update, we will deploy `chains/coreum` after v0.47 update. In this case we might not even need this change. 

___
___
*[`cmd/parse/gov/proposal.go` line 44 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41#-NkQ83V50MI-7P38rhk7:-NkQ83V50MI-7P38rhk8:b-x5uzq4) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/cda783ccc28ee88da07d2a02b5b456828c97b31f/cmd/parse/gov/proposal.go#L44)):*
> ```Go
> 			// Build the gov module
> 			govModule := gov.NewModule(config.Cfg, sources.GovSource, nil, nil, nil, nil, nil, nil, nil, nil, nil, parseCtx.EncodingConfig.Marshaler, db)
> 			if err != nil {
> ```

it is no returning an error, so why are we checking for error ?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @keyleu, and @wojtek-coreum)

___
*[`modules/gov/handle_msg.go` line 165 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41#-NkQ2_oHDr2TSn_8_EvU:-NkQKJQJ373Lgr3RwdpU:bmbiukc) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/cda783ccc28ee88da07d2a02b5b456828c97b31f/modules/gov/handle_msg.go#L165)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

no? What if the height is different than the one when tx was executed?
</blockquote></details>

height 0 means latest height I guess.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41)* status: all files reviewed, 3 unresolved discussions (waiting on @keyleu, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41#-NkQGisd7zWiVddK7Yuq:-NkU2vxc3vy2Ur5rgJ01:bcppo66) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

The PR is made agains `chains/coreum` branch which contains v0.47 cosmos sdk update, we will deploy `chains/coreum` after v0.47 update. In this case we might not even need this change.
</blockquote></details>

Right, updated.

___
___
*[`cmd/parse/gov/proposal.go` line 44 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41#-NkQ83V50MI-7P38rhk7:-NkU3iO_8NauMjydVPSu:ba3hre5) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/cda783ccc28ee88da07d2a02b5b456828c97b31f/cmd/parse/gov/proposal.go#L44)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it is no returning an error, so why are we checking for error ?
</blockquote></details>

Remvoed
___
*[`modules/gov/handle_msg.go` line 165 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41#-NkQ2_oHDr2TSn_8_EvU:-NkU3lhJAG4PePHG61Jx:bo13ux7) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/cda783ccc28ee88da07d2a02b5b456828c97b31f/modules/gov/handle_msg.go#L165)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

height 0 means latest height I guess.
</blockquote></details>

Yes, height 0 means latest height. So in that case we will get the latest state of the proposal, which is what we need.

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu and @miladz68)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/41)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu)

**Pull request merged**
