### PR TITLE
feat: Integrate asset FT and NFT params indexing.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/12)

### CODE REVIEW

**Review by miladz68 — DISMISSED** [review]
I have no idea how this works under the hood. I will approve but please make sure manually that it works as intended. 

> Reviewed 32 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/12#-:-NQ4pOxW-bwClBrpnRMo:b-c8w2x3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 32 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/12)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @wojtek-coreum)

___
*[`modules/registrar.go` line 88 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/12#-NQ4wkAo4qQstqE8SIWH:-NQ4wkAo4qQstqE8SIWI:bljyku0) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/f0ffcf9b98776089c5e959cc3f27ea1da73b2aa3/modules/registrar.go#L88)):*
> ```Go
> 	feeModelModule := feemodel.NewModule(sources.FeeModelSource, cdc, db)
> 	customParamsModule := customparams.NewModule(sources.CustomParamsSource, cdc, db)
> 	asserFTModule := assetft.NewModule(sources.AsserFTSource, cdc, db)
> ```

asser -> asset

**Review by dzmitryhil — COMMENTED** [review]
It works manually. I tested it.

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/12#-:-NQ4x96q6979xgluAe3e:b-b7hllu)* status: 27 of 32 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`modules/registrar.go` line 88 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/12#-NQ4wkAo4qQstqE8SIWH:-NQ4xt_DDh1T6_WHy4GT:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/f0ffcf9b98776089c5e959cc3f27ea1da73b2aa3/modules/registrar.go#L88)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

asser -> asset
</blockquote></details>

Done.

**Review by ysv — DISMISSED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Pull request merged**
